#  Copyright (c) 2023.  OCX Consortium https://3docx.org. See the LICENSE
# Module specific config settings
WIKI_URL : "https://ocxwiki.3docx.org/"
TEST_WIKI_URL: "https://ocxwiki.astrup.info/"
DEFAULT_NSP : "ocx"
WORKING_DRAFT: 'https://3docx.org/fileadmin//ocx_schema//V300b0//OCX_Schema.xsd'
SCHEMA_FOLDER: 'tmp'
REPORT_FOLDER: "reports"
VALIDATOR: "http://localhost:8080"
RESOURCES: "resources"
XSLT_EN: "gitb_trl_stylesheet_v1.0.xsl"
DOCKER_CONTAINER: "validator"
DOCKER_IMAGE: "3docx/validator"
DOCKER_DESKTOP: "C:/Program Files/Docker/Docker/Docker Desktop.exe"
